mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: amdb
    MYSQL_USER: user
    MYSQL_PASSWORD: password
memcached:
  image: memcached
  ports:
    - "11211:11211"
